apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test88
  description: Replace me with a real description.
  annotations:
    github.com/project-slug: test-backstage
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: ml-team
